without electron
(2.1)
H2 <-> 2 H + 0 C + 0 O
CO <-> 0 H + 1 C + 1 O
CH4 <-> 4 H + 1 C + 0 O
H2O <-> 2 H + 0 C + 1 O

(2.2)
n_H2   = K_H2* x_H^2* x_C^0* x_O^0
n_CO   = K_CO*  x_H^0* x_C^1* x_O^1
n_CH4  = K_CH4* x_H^4* x_C^1* x_O^0 
n_H2O  = K_H2O* x_H^2* x_C^0* x_O^1 

(2.3)
ep_H xbH = xH + 4 n_CH4 + 2 n_H2O
ep_C xbH = xC + n_CO + n_CH4
ep_O xbH = xO + n_CO + n_H2O

In [1]:
import numpy as np
import jaxopt

In [2]:
elem_=np.array(["H","C","O"])
spec_=np.array(["H2","CO","CH4","H2O"])

In [3]:
nu=np.array([[2,0,0],[0,1,1],[4,1,0],[2,0,1]]) #(2.1) formula matrix

In [4]:
def ni(x,nu,K):
    """law of mass action
    
    Returns:
        species number density
    """
    return K*np.prod(x0**nu,axis=1)

In [5]:
def en(x,nu,K):
    """(2.3)
    
    Returns:
        total element number density
    """
    return x+nu.T@ni(x,nu,K)

In [6]:
x0=np.array([0.1,0.2,0.3])
K=np.array([1,1,1,1])

In [7]:
enin=np.array([1.0,0.2,0.1])

In [8]:
en(x0,nu,K)

array([0.12608, 0.26002, 0.363  ])

In [9]:
def f(x):
    return np.sum((en(x,nu,K)-enin)**2)

In [10]:
gd = jaxopt.GradientDescent(fun=f, maxiter=500)

In [11]:
params, state = gd.run(init_params=np.random.rand(len(x0)))

In [12]:
xast=params

In [13]:
en(xast,nu,K)

DeviceArray([1. , 0.2, 0.1], dtype=float32)

In [14]:
enin

array([1. , 0.2, 0.1])